### ISSUE TITLE
verify available helm charts for the current marketplace

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/vdc#12]
https://github.com/threefoldtech/marketplace-charts/
right now we have, let's see what is already available in helm and test them out

- [x] discourse @AhmedSa-mir moved out to the backlog
- [x] cryptpad #32 
- [x] taiga #34 
- [x] peertube @OmarElawady currently working #35 
- [x] mattermost @waleedhammam currently working #36 
- [x] gitea @ashraffouda  @RafyAmgadBenjamin #37 
- [x] zeroci #46

**Comment by AhmedSa-mir** [comment]
Packages already on helm hub:
- [Discourse](https://artifacthub.io/packages/helm/bitnami/discourse)
- [Mattermost](https://artifacthub.io/packages/search?page=1&ts_query_web=mattermost) 
- [Gitea](https://artifacthub.io/packages/search?page=1&ts_query_web=gitea) - (Should we add our auth in a?)

**Comment by AhmedSa-mir** [comment]
Cryptpad: https://github.com/threefoldtech/marketplace-charts/tree/master/charts/cryptpad

**Comment by AhmedHanafy725** [comment]
Every helm chart should set (request, limit) for memory and CPU, to not run out of resources.

**Comment by AhmedSa-mir** [comment]
@AhmedHanafy725  https://github.com/threefoldtech/js-sdk/issues/1692

**Comment by waleedhammam** [comment]
will work on matter most

**Comment by OmarElawady** [comment]
will work on peertube

**Comment by dmahmouali** [comment]
For now, there's a [base chatflow](https://github.com/threefoldtech/js-sdk/blob/d602a230ac3b063b6d289fe095e35810ced1a814/jumpscale/packages/marketplacevdc/sals/solutions_chatflow.py) you can inherit it for test the solution chart in a chatflow and here a [base docs](https://github.com/threefoldtech/js-sdk/blob/d602a230ac3b063b6d289fe095e35810ced1a814/docs/wiki/tutorials/add_marketplacevdc_chatflow.md) for:
Changes:
- Update the cluster data that required [here](https://github.com/threefoldtech/js-sdk/blob/d602a230ac3b063b6d289fe095e35810ced1a814/jumpscale/packages/marketplacevdc/sals/solutions_chatflow.py#L34)
- Added the configurations in `self.chart_config` like [here in cryptpad](https://github.com/threefoldtech/js-sdk/blob/d602a230ac3b063b6d289fe095e35810ced1a814/jumpscale/packages/marketplacevdc/chats/cryptpad.py#L22) as the chart require
---
Then the base chatflow will:
- Create subdomain
- Expose the k8s cluster added its configurations in `self.vdc_obj`
- Deploy the chart

**Comment by xmonader** [comment]
moving the publishing tools out of this issue

**Comment by xmonader** [comment]
now discourse is available i'll close the issue, if any troubles with discourse let's move to next
